# roles/dns/tasks/main.yml
---
# Tasks for controller node
- name: Install BIND DNS server on controller
  apt:
    name:
      - bind9
      - bind9utils
    state: present
  become: yes
  when: inventory_hostname in groups['controller']

- name: Configure BIND zone files on controller
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: bind
    mode: '0644'
  with_items:
    - { src: 'db.slurm-cluster.j2', dest: '/etc/bind/db.slurm-cluster' }
    - { src: 'db.192.168.64.j2', dest: '/etc/bind/db.192.168.64' }
  become: yes
  notify: restart bind
  when: inventory_hostname in groups['controller']

- name: Configure BIND options on controller
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  become: yes
  notify: restart bind
  when: inventory_hostname in groups['controller']

- name: Configure BIND local zones on controller
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  become: yes
  notify: restart bind
  when: inventory_hostname in groups['controller']

# Tasks for all nodes
- name: Configure DNS client on all nodes
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart resolved

- name: Ensure systemd-resolved is using our DNS config
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  become: yes